spring.application.name=user-account-service
server.port=8081

#POSTGRES DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/novabank_users_account_db
spring.datasource.username=postgres
spring.datasource.password=root

#JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update
