spring.application.name=user-account-service
server.port=8081

#POSTGRES DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/novabank_users_account_db
spring.datasource.username=postgres
spring.datasource.password=root

#JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update

# JWT config
jwt.secret=your_very_long_and_very_secure_secrete_key_for_authentication_it_should_be_at_least_64_characters_long
jwt.expiration=86400000

#kafka config
spring.kafka.bootstrap-servers=localhost:9092

#Kafka Config as a Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type=true